### ISSUE TITLE
Component slots

### ISSUE THREAD

**Issue by Ubugeeei** [vuejs/core-vapor#154]
- [x] `<slot>` in child component
  - #170 
  - #182
- [x] pass slot from parent component
  - [Demo](https://vapor-repl.netlify.app/#__VAPOR__eNp9UstOwzAQ/BXLHEKlKjnAqQqVAPUAB0CAOOUSkm3q1rEtexOCqvw7azcpKQIiRdrH7GpmvHt+bUzcNsAXPHWFFQaZA2wMk7mqrjKOLuPLTInaaIvsVteGra2uWRQnPvGjUabS5DBLSEoQaiNzBMoYSz0sRBS/N4haLfUuTYYwQMIqCtNkMsrnXKgSuniDtZzQw08DRKzWZSMhkPOr/TeQ3LPCAu14yykleawfKBPXpPVFYvxjxsNGXYMjE9DpvnP6Z3GtG4Xn0VluTDQ76k9L0TJREj+qE7k0ocKSpKArtFqLKt46rUjN3m/PeEHChQT7aFBoRV4vWOj4Xi6l/rgPNbQNzMd6sYFi90t96zpfy/iTBQe2JXOOPcxtBXhor14eoKP42Byt/Kf5DE7LxnM8wG4aVRLtCS6wvQtuClW9ulWHoNwoyhP1yD7gM07++jf/S/o33Yv4MsxlqicXx5Pz53B6ZU5qZMnpDfH+Cysu8Lo=)
  - [x] static slot / dynamic named slot
    - #202
    - #203 
  - [x] slot props
    - #223 
    - #227 
  - [x] slot + v-if / v-else / v-else-if
    - #207
  - [x] slot + v-for
    - #207 
  - [x] perf dynamic slots, finer update granularity
    - #222

**Comment by LittleSound** [comment]
I am trying to implement this issue, I noticed that currently slot outlets need to be obtained through the instance, do we need to create a `createSlot` function to handle this?

```javascript
function render(_ctx) {
 // some codess

  const n3 = _createSlot('default', {
    foo: ()=> _ctx.bar
  }, () => {
    return _template('<div>fallback content</div>')
  })

 // some codes
}
```

**Comment by Ubugeeei** [comment]
Considering props and attrs as well, it might be better to have a function that directly references the instance or a function for accessing parts of it, rather than creating createSlot. 🤔
getCurrentInstance, or getSlots, getAttrs, getProps, .... 🤔 🤔

What do you think? cc @sxzz

**Comment by LittleSound** [comment]
I think it is necessary, because for complex requirements such as dynamic slot outlets, encapsulating functions can reduce the complexity of generating code.

**Comment by Ubugeeei** [comment]
Indeed. That might be better.

**Comment by sxzz** [comment]
I think `createSlots` is a proper abstraction considering scope slot is a pretty complex feature.

**Comment by LittleSound** [comment]
We have available slot features. Next, I will focus more on the related lifecycle hooks.
