### ISSUE TITLE
`v-model`

### ISSUE THREAD

**Issue by Ubugeeei** [vuejs/core-vapor#17]
br: https://github.com/Ubugeeei/vuejs-core/tree/feat/v-model

**Comment by baiwusanyu-c** [comment]
v-show and v-model need to be based on runtime design. Currently, the team needs to discuss the design plan before they can be implemented.

**Comment by Ubugeeei** [comment]
Thank you for sharing!
I’ll play around with it a bit, assuming we’ll redo it once things are decided.

**Comment by sxzz** [comment]
Need #19 first

**Comment by sxzz** [comment]
`v-model` for native is completed, the next step is about components. Let's track #127

**Comment by WORMSS** [comment]
I am getting `The requested module 'vue' does not provide an export named 'useModel'` from the vapor-repl [playground on netlify](https://vapor-repl.netlify.app/)

All I am doing is adding `const m = defineModel()` to the default playground..

I am not sure the vue files hosted there are old, or if v-model and defineModel are more disconnected than I thought and I just need to wait longer?

**Comment by sxzz** [comment]
`useModel` has not ported from Vue core, and we should wait for a bit longer.

**Comment by WORMSS** [comment]
That is fine, it explains what I am seeing, and makes sense.. It doesn't seem to be on the roadmap on the README, is there a good issue/pr/thread/newsletter/carrier pigeon I should keep an eye out for?

**Comment by sxzz** [comment]
`defineModel`/`useModel` is working with bundlers, but not for SFC playground, due to CDN imports. You can try it with bundler, see [template](https://github.com/sxzz/vue-vapor-demo)

For CDN import, I created an issue #145 for tracking.
