### ISSUE TITLE
Is Vapor going to work with setup render function components

### ISSUE THREAD

**Issue by zdravkov** [vuejs/core-vapor#228]
Hi,
Seems like a great effort so far!

Not sure if this is the right place to ask (if it is not please correct me :)) but is Vapor mode thought/designed to support 
setup render function components (or setup with jsx components) our of the box?

Greetings,
Plamen

**Comment by sxzz** [comment]
Currently, Vue Vapor only supports writing `<script setup>` in SFC (`.vue`). Future support for JSX is under consideration, with details yet to be determined.
