### ISSUE TITLE
`createIf` doesn't update

### ISSUE THREAD

**Issue by xiaodong2008** [vuejs/core-vapor#257]
`createIf` only updates when passing a context ref.

```diff
const value = ref(true)
const Parent = {
  render() {
    return createComponent(Child)
  },
}
const Child: Component = {
+ setup() {
+   return { value }
+ },
  render(_ctx) {
    return createIf(() => _ctx.value, template(`<div>`), template(`<span>`))
  },
}
const { html, serialize } = define(Parent).render()
value.value = false
await nextTick()
console.log(html()) // Doesn't change when without setup
```

**Comment by GaoNeng-wWw** [comment]
![Snipaste_2024-06-26_10-59-50](https://github.com/vuejs/core-vapor/assets/31283122/c9578767-82fd-4a12-b996-9c87d2a8d9f0)

It doesn't look like bug

git commit: `5eb43b08`

**Comment by xiaodong2008** [comment]
> ![Snipaste_2024-06-26_10-59-50](https://private-user-images.githubusercontent.com/31283122/342992535-c9578767-82fd-4a12-b996-9c87d2a8d9f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MzI0MjIsIm5iZiI6MTcxOTgzMjEyMiwicGF0aCI6Ii8zMTI4MzEyMi8zNDI5OTI1MzUtYzk1Nzg3NjctODJmZC00YTEyLWI5OTYtOWM4N2QyYThkOWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDExMDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MDE5MGEzYjU4ZDUxODIxZDQ5MjAyNWNiZTFiZjdiYmY3NWNkZTg5NTJjNzkzMGZmOWUxOTE4YzgzODA4M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cEF0B6JnKqdDlJS0qL_DbwtaohzGw1vyWYa7kz-QOus)
> 
> It doesn't look like bug
> 
> git commit: `5eb43b08`

Reproduce:
```typescript
const value = ref(true)
const Parent = {
  render() {
    return createComponent(Child)
  },
}
const Child: Component = {
  render() {
    return createIf(() =>value, template(`<div>`), template(`<span>`))
  },
}
const { html, serialize } = define(Parent).render()
value.value = false
await nextTick()
console.log(html()) // Doesn't change when without setup
```

**Comment by moushicheng** [comment]
@xiaodong2008 
Hello,it seems not a bug 
in component Child, you must use value.value instead of value to track effect.
```ts
  render() {
    return createIf(() => value.value, template(`<div>`), template(`<span>`))
  },
```
