### ISSUE TITLE
`createSelector`

### ISSUE THREAD

**Issue by LittleSound** [vuejs/core-vapor#277]
Discuss whether `createSelector` is needed to optimize performance.

Using functions like `createSelector` can reduce the time complexity of the select row item in [the benchmark](https://krausest.github.io/js-framework-benchmark/2024/table_chrome_127.0.6533.72.html) from `O(n)` to `O(1)`.

### Use `createSelector` in other frameworks

Here is some information about `createSelector` in other frameworks:

- [SolidJS -- createSelector](https://docs.solidjs.com/reference/secondary-primitives/create-selector)

- [VueRX JSX -- createSelector](https://github.com/ryansolid/vuerx-jsx/blob/e8ced854b3f22dbcadbd6fd965c48c6b2363f7ce/src/lib.ts#L85-L111)

- [The simple attempts of createSelector with Vapor](https://github.com/krausest/js-framework-benchmark/pull/1729/files#diff-ba4aeb78897bc14d6b6a5ec7ec41e8c0c445d0e0b071e50ec4a0041b27c0fb16R59-R67) -- krausest/js-framework-benchmark#1729

### Use `v-memo` in Vue

It is important to note when using `v-memo` in Vue. We can achieve a similar effect:

```vue

<div v-for="item in list" :key="item.id" v-memo="[item.label, item.id === selected]">
  <p>{{ item.id }}: {{ item.label }} - selected: {{ item.id === selected }}</p>
  <p>...more child nodes</p>
</div>

```

Since v-memo is a more general API, the user experience will be somewhat different because you need to specify content other than `id`, such as `item.label`.

So what are your thoughts on this? Feel free to discuss.

**Comment by LittleSound** [comment]
> CSS has already defined _Selector_, perhaps we need a more unique name?

Do you have any suggested names?

**Comment by icarusgk** [comment]
Being able to reduce time complexity from `O(n)` to `O(1)` is truly a great feat, wow. Would this be available to the users, or will it be used as an internal API?

**Comment by sxzz** [comment]
Like Solid.js, I believe `createSelector` should be public API and used for performance-sensitive cases.

**Comment by sxzz** [comment]
Done via #279
