### ISSUE TITLE
Component LifeCycles

### ISSUE THREAD

**Issue by Ubugeeei** [vuejs/core-vapor#31]
related: https://github.com/vuejs/core-vapor/issues/4

# LifeCycles

Currently, we are working on Props in parallel with https://github.com/vuejs/core-vapor/issues/25, 
but it seems that we can proceed with LifeCycles on a separate axis, so we will continue with it during the discussion as well.

Some implementations seem to be able to start, while others cannot be started yet or require discussion. 
If you have editing rights for this comment, please add the situation to the Todo.

## Todo
- [x] onBeforeMount
- [x] onMounted
    https://github.com/vuejs/core-vapor/pull/46
- [x] onUnmounted
    https://github.com/vuejs/core-vapor/pull/46
- [x] onBeforeUnmount
- [x] onUpdated
  https://github.com/vuejs/core-vapor/pull/89
- [x] onBeforeUpdate
  https://github.com/vuejs/core-vapor/pull/89
- [x] onErrorCaptured
  https://github.com/vuejs/core-vapor/pull/71
- [x] onRenderTracked
  #183 
- [x] onRenderTriggered
  #183 
- [ ] onActivated
- [ ] onDeactivated
- [ ] onServerPrefetch

**Comment by Ubugeeei** [comment]
related: https://github.com/vuejs/core-vapor/pull/43

**Comment by Ubugeeei** [comment]
NOTE: 
It seems there are a few people trying to implement the onUpdated hook, 
but it might be better to discuss it here first. Starting from the design.

**Comment by sxzz** [comment]
We need to wait PR https://github.com/vuejs/core-vapor/pull/82 to refactor reactivity system.

**Comment by GaoNeng-wWw** [comment]
> NOTE: It seems there are a few people trying to implement the onUpdated hook, but it might be better to discuss it here first. Starting from the design.

i think we can use `MutationObserver` watch instance state(attr/characterData/subtree/children).When changes occur, trigger the update hook

detail: https://github.com/vuejs/core-vapor/pull/87

**Comment by LittleSound** [comment]
I integrated the Render Watch API in #86. To implement the Updated And BeforeUpdate Hooks, I will emit update events within this Render Watch API.

**Comment by Ubugeeei** [comment]
This issue is probably sufficiently covered by https://github.com/vuejs/core-vapor/issues/197. cc @sxzz
