### ISSUE TITLE
Component Slots

### ISSUE THREAD

**Issue by Ubugeeei** [vuejs/core-vapor#53]
related: #4

**Comment by sxzz** [comment]
Big thanks for awesome your contribution! However, we need to slow down due to my working schedule.

**Comment by Ubugeeei** [comment]
Ok, I'll wrap up what I've done so far with this issue's note and take a break.  😴 
If there's anything low-effort you'd like me to do first, please don't hesitate to ask. (Like adding small tests, etc.)

**Comment by sxzz** [comment]
Continues in #154
