### ISSUE TITLE
[Runtime] Implement Full `watchEffect` Functionality in Vue Vapor

### ISSUE THREAD

**Issue by LittleSound** [vuejs/core-vapor#67]
The current implementation of `effect` within the vue-vapor project does not fully conform to the standard `watchEffect` behavior, particularly lacking in comprehensive `flush` timing options.

We aim to align vue-vapor's `watchEffect` with the standard version by introducing detailed `flush` options (`pre`, `post`, `sync`). A fully realized `flush` mechanism will facilitate the implementation of the [`beforeUpdate` directive lifecycle hook](https://github.com/vuejs/core-vapor/pull/60).
In addition, we plan to introduce a new `onEffectCleanup` API analogous to [`onScopeDispose`](https://vuejs.org/api/reactivity-advanced.html#getcurrentscope), which will aid in implementing [dynamic arguments for `v-on`](https://github.com/vuejs/core-vapor/pull/60). first, extend `watchEffect` in the runtime-vapor package. If necessary later, extract it to the reactivity package.

**Comment by 1049906948** [comment]
强
