### ISSUE TITLE
[Runtime] The command hook should return the component instance proxy

### ISSUE THREAD

**Issue by baiwusanyu-c** [vuejs/core-vapor#74]
https://github.com/vuejs/core-vapor/blob/597eae423b0d69fba47b0ac6a1e9692fb4a95f71/packages/runtime-core/src/directives.ts#L92-L94

Should be consistent with the existing runtime, returning a proxy object for the component instance

**Comment by sxzz** [comment]
Most properties of public instances benefit from the Options API. I think that when only Composition API is supported, these properties can be obtained using macros `defineXXX` or `getCurrentInstance`.

Also, we can plan to publicize some properties returned by `getCurrentInstance`.

**Comment by sxzz** [comment]
At this stage, we can avoid public instances and consider not distinguishing between internal and public in the future.
