### ISSUE TITLE
[Runtime]: cannot access `props`, `attrs`, `emits` from render function

### ISSUE THREAD

**Issue by Ubugeeei** [vuejs/core-vapor#84]
related: https://github.com/vuejs/core-vapor/pull/47#issuecomment-1869042881

I implemented Component's Proxy in [the PR that implements props](https://github.com/vuejs/core-vapor/pull/40/files#diff-f14a9228110d02549792f3bbbc1ba70a9a38b05635116038c73d4fd7c8a9ee7fR36), but found that it was erased in [this commit](https://github.com/vuejs/core-vapor/commit/efc32b716fece04e3c5e7035f2bffc0327d4b347).

Without it, I don't know how to access props from the render function, since the ctx I receive as argument to the render function does not include props.

this issue blocks https://github.com/vuejs/core-vapor/issues/81, https://github.com/vuejs/core-vapor/pull/42, https://github.com/vuejs/core-vapor/pull/47, https://github.com/vuejs/core-vapor/pull/54

---

I am assuming the following code, or am I wrong? 🤔 

```ts
const Comp = defineComponent({
  props: ['foo'],
  setup() {
    const __returned__ = {}
    Object.defineProperty(__returned__, '__isScriptSetup', {
      enumerable: false,
      value: true,
    })
    return __returned__
  },
  render(_ctx: any) {
    const t0 = template('<div></div>')
    const n0 = t0()
    const {
      0: [n1],
    } = children(n0)
    watchEffect(() => {
      setText(n1, void 0, _ctx.foo) // here!
    })
    return n0
  },
})
```

**Comment by Ubugeeei** [comment]
@sxzz 
I need a response when you have time. 🙏🏻

**Comment by sxzz** [comment]
Let's discuss about public instance here https://github.com/vuejs/core-vapor/issues/74#issuecomment-1889842517

**Comment by Ubugeeei** [comment]
！！
Ok! Thanks!
